; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Bootsmann"
#define MyAppVersion "0.1.0 (64 bit)"
#define MyAppPublisher "BootsmannApp"
#define MyAppURL "https://github.com/BootsmannApp/bootsmann"
#define MyAppExeName "bootsmann.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{687D6954-1E50-402F-94AB-5A0161E4F0EA}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultGroupName={#MyAppName} {#MyAppVersion}
AllowNoIcons=yes
LicenseFile=..\..\LICENSE
SetupIconFile=..\icon.ico
Compression=lzma
SolidCompression=yes

ArchitecturesInstallIn64BitMode=x64
OutputDir=_output
OutputBaseFilename=bootsmann-0.1-setup-64bit
DefaultDirName={pf}\Bootsmann

VersionInfoDescription=Bootsmann Installer
VersionInfoCopyright=© 2025 BootsmannApp
VersionInfoVersion=0.1.0.0

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "german"; MessagesFile: "compiler:Languages\German.isl"
;Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"
;Name: "ukrainian"; MessagesFile: "compiler:Languages\Ukrainian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; 

[Files]
;Source: "bin64\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "_output\bin\*"; DestDir: "{app}\bin"; Flags: ignoreversion recursesubdirs createallsubdirs                                                        
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
;Source: "..\build_msvc_2022_64\vc_redist.x64.exe"; DestDir: {tmp}; Flags: deleteafterinstall

Source: "..\..\LICENSE"; DestDir: "{app}"
Source: "..\..\CHANGES"; DestDir: "{app}"
Source: "..\..\README.md"; DestDir: "{app}"
;Source: "..\..\examples\*"; DestDir: "{app}\examples"; Flags: ignoreversion recursesubdirs createallsubdirs
;Source: "..\3rdParty\tools\*"; DestDir: "{app}\tools"; Flags: ignoreversion recursesubdirs createallsubdirs

Source: ".\msvc\*"; DestDir: {tmp};

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: desktopicon
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: desktopicon

Name: "{group}\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"
;Name: "{group}\Bootsmann\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
;Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\bin\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: {tmp}\vcredist2015_2017_2019_2022_x64.exe; \
    Parameters: "/q /passive /Q:a /c:""msiexec /q /i vcredist.msi"""; \
    StatusMsg: "Installing Microsoft Visual C++ 2015-2022 Redistributables (x64)..."; \
    Flags: runhidden waituntilterminated

Filename: "{app}\bin\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
